#!/bin/bash

mysql -h ${MYSQL_DATABASE_HOST} -P ${MYSQL_DATABASE_PORT} -uroot -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS ${PDNS_ADMIN_DATABASE}"

#Grant Remote Permissions
mysql -h ${MYSQL_DATABASE_HOST} -P ${MYSQL_DATABASE_PORT} -uroot -p${MYSQL_ROOT_PASSWORD} -e "GRANT ALL PRIVILEGES ON ${PDNS_ADMIN_DATABASE}.* To '${PDNS_ADMIN_USER}'@'localhost' IDENTIFIED BY '${PDNS_ADMIN_PASSWORD}'"
mysql -h ${MYSQL_DATABASE_HOST} -P ${MYSQL_DATABASE_PORT} -uroot -p${MYSQL_ROOT_PASSWORD} -e "GRANT ALL PRIVILEGES ON ${PDNS_ADMIN_DATABASE}.* To '${PDNS_ADMIN_USER}'@'%' IDENTIFIED BY '${PDNS_ADMIN_PASSWORD}'"

echo "Configuring APP"
cd $PDNSADMIN_DIR
cp config_template.py config.py
sed "s,BIND_ADDRESS = '127.0.0.1',BIND_ADDRESS = '0.0.0.0',g" -i $PDNSADMIN_DIR/config.py
sed "s,PDNS_STATS_URL = 'http://172.16.214.131:8081/',PDNS_STATS_URL = '$PDNSADMIN_APIURL',g" -i $PDNSADMIN_DIR/config.py
sed "s,PDNS_API_KEY = 'you never know',PDNS_API_KEY = '$PDNSADMIN_APIKEY',g" -i $PDNSADMIN_DIR/config.py
sed "s,PDNS_VERSION = '3.4.7',PDNS_VERSION = '$PDNS_VERSION',g" -i $PDNSADMIN_DIR/config.py
sed "s,SQLALCHEMY_DATABASE_URI = 'mysql://root:123456@192.168.59.103/pdns',SQLALCHEMY_DATABASE_URI = 'mysql://$PDNS_ADMIN_USER:$PDNS_ADMIN_PASSWORD@$MYSQL_DATABASE_HOST/$PDNS_ADMIN_DATABASE',g" -i $PDNSADMIN_DIR/config.py
sed "s,PORT = 9393,PORT = $PDNSADMIN_PORT,g" -i $PDNSADMIN_DIR/config.py
sed "s,TIMEOUT = 10,TIMEOUT = 60,g" -i $PDNSADMIN_DIR/config.py
sed "s/RECORDS_ALLOW_EDIT = \['A', 'AAAA', 'CNAME', 'SPF', 'PTR', 'MX', 'TXT'\]/RECORDS_ALLOW_EDIT = \['A', 'AAAA', 'CNAME', 'SPF', 'PTR', 'MX', 'TXT', 'SRV', 'SOA', 'NS'\]/" -i $PDNSADMIN_DIR/config.py

echo "Starting APP"
/opt/PowerDNS-Admin/run.py
